### ISSUE TITLE
Making the App Responsive and Look Good on Mobile Devices

### ISSUE THREAD

**Issue by kenmazaika** [gagaception/splurty#1]
On mobile things don't look as good as they could be.

One thing you could look into is to add the "mobile meta tag" to your app, so the responsive effect of Bootstrap actually shows up on Mobile.

Let me know in the comments once you figured that step out :)

**Comment by gagaception** [comment]
Made some changes, is it ok now?
Сб, 22 авг. 2015 г. в 18:31, ken mazaika notifications@github.com:

**Comment by kenmazaika** [comment]
The change should happen in `application.html.erb` to add a single line, called the viewport meta tag:
http://www.w3schools.com/css/css_rwd_viewport.asp

Hope this helps!

**Comment by gagaception** [comment]
I added this change right after your first letter, and on my phone it works
properly. Here's a screenshot Just a little bit confused: was your second
letter came with delay or my app doesn't work properly on your device?

Сб, 22 авг. 2015 г. в 19:10, ken mazaika notifications@github.com:

**Comment by gagaception** [comment]
I added this change right after your first letter, and on my phone it works
properly. Here's a screenshot Just a little bit confused: your second
letter came with delay or my app doesn't work properly on your device?

Сб, 22 авг. 2015 г. в 19:10, ken mazaika notifications@github.com:

**Comment by gagaception** [comment]
Сб, 22 авг. 2015 г. в 19:21, Aziz Sharipov sharipov.aziz.sh@gmail.com:

**Comment by kenmazaika** [comment]
Solid!  Thumbs up! :+1:

**Comment by kenmazaika** [comment]
I missed the line in your code!  Sorry for the false alert!  Keep up the good work coding.

**Comment by gagaception** [comment]
Thanks )
Сб, 22 авг. 2015 г. в 19:27, ken mazaika notifications@github.com:
